### ISSUE TITLE
Authorizing App Properply (Client-Side)

### ISSUE THREAD

**Issue by KalibRx** [timekit-io/js-sdk#48]
I am writing an app in Ionic. I have read through the docs and can't find a way to authenticate properly with an API key (without booking-js). Only credentials. The only way to authenticate in the examples in the repo is with a plaintext username and password. This is obviously unacceptable in a mobile app. How might I authenticate given my situation?

**Comment by laander** [comment]
@KalibRx I'm sorry for the delayed reply, I recommend that you contact us on our in-app chat or yourfriends@timekit.io next time.

That said, there's a few things to consider when developing mobile apps. First of, mobile apps are considered clients, just like web browser, because code runs on your user's device. This means that API keys saved on in the app in effect are public and not secret. Even though the app code can be compiled, network calls can still be monitored and request headers intercepted.

For this reason, we recommend that you only make API calls to Timekit through a backend proxy. So: Mobile app > Your backend > Timekit API. If you don't want to introduce a fully fledged backend setup, serverless functions is a great lightweight alternative - check out https://zeit.co/now or https://webtask.io/

In your serverless function, you'd initialize the SDK like so:
```
timekit.configure({
  appKey: 'live_api_key_4cY2KWMggw95mAdx51eYUO2CyIWI2xup'
})
```

And you'd expose the Timekit API calls through a function's endpoint that the app will call. Remember that security (permissions, roles etc) is your responsibility as our API key gives full access to all your app data.

Sidenote: we actually still support resource-specific resource keys that only grants access to a specific resource's data. This might be used directly in a mobile app if you take care to provide the right keys when your users login to your app.
